import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/webapi/voucherly",
    },
    {
      type: "category",
      label: "Companies",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/webapi/schemas/company",
          label: "Company",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/webapi/create-company",
          label: "Create a Company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/webapi/retrieve-company",
          label: "Retrieve a Company",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Customers",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/webapi/schemas/customer",
          label: "Customer",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/webapi/create-customer",
          label: "Create a Customer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/webapi/list-customer",
          label: "List all Customers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/webapi/retrieve-customer",
          label: "Retrieve a Customer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/webapi/update-customer",
          label: "Update a Customer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/webapi/list-customer-payment-method",
          label: "List a Customer's PaymentMethods",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/webapi/delete-customer-payment-method",
          label: "Delete a Customer's PaymentMethod",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Payments",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/webapi/schemas/payment",
          label: "Payment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/webapi/create-payment",
          label: "Create a Payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/webapi/retrieve-payment",
          label: "Retrieve a Payment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/webapi/confirm-payment",
          label: "Confirm a Payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/webapi/refund-payment",
          label: "Refund a Payment",
          className: "api-method post",
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Customers",
    //   collapsible: true,
    //   collapsed: true,
    //   items: [
    //     {
    //       type: "doc",
    //       id: "api/webapi/list-a-customers-addresses",
    //       label: "List a Customer's Addresses",
    //       className: "api-method get",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/create-a-customers-address",
    //       label: "Create a Customer's Address",
    //       className: "api-method post",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/retrieve-a-customers-address",
    //       label: "Retrieve a Customer's Address",
    //       className: "api-method get",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/update-a-customers-address",
    //       label: "Update a Customer's Address",
    //       className: "api-method put",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/delete-a-customers-address",
    //       label: "Delete a Customer's Address",
    //       className: "api-method delete",
    //     },
    //   ],
    // },
    {
      type: "category",
      label: "Payment Gateways",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "api/webapi/list-payment-gateway",
          label: "List all PaymentGateways",
          className: "api-method get",
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Schemas",
    //   collapsible: true,
    //   collapsed: true,
    //   items: [
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/id",
    //       label: "Id",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/customerwallettotals",
    //       label: "CustomerWalletTotals",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/creditcardinfo",
    //       label: "CreditCardInfo",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/directdebitinfo",
    //       label: "DirectDebitInfo",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/metadata",
    //       label: "Metadata",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paginationresponse",
    //       label: "PaginationResponse",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentstatus",
    //       label: "Payments.PaymentStatus",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/problemdetails",
    //       label: "ProblemDetails",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/tenantmode",
    //       label: "TenantMode",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentgateways-checkoutaction",
    //       label: "PaymentGateways.CheckoutAction",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/companyaddressforexternalapi",
    //       label: "CompanyAddressForExternalApi",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentmethod",
    //       label: "PaymentMethod",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentgateways-checkout-paymentrequest",
    //       label: "PaymentGateways.Checkout.PaymentRequest",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/services-paymentgateways-paymentgatewaydto",
    //       label: "Services.PaymentGateways.PaymentGatewayDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/services-paymentgateways-paymentgatewayparameterdto",
    //       label: "Services.PaymentGateways.PaymentGatewayParameterDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentgateways-paymentgatewayparameteroptiondto",
    //       label: "PaymentGateways.PaymentGatewayParameterOptionDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentgateways-paymentgatewaytype",
    //       label: "PaymentGateways.PaymentGatewayType",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentmode",
    //       label: "Payments.PaymentMode",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-externalerror",
    //       label: "Payments.ExternalError",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentclosecheckout",
    //       label: "Payments.PaymentCloseCheckout",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentlastcallback",
    //       label: "Payments.PaymentLastCallback",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentdiscount",
    //       label: "Payments.PaymentDiscount",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-discounttype",
    //       label: "Payments.DiscountType",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentline",
    //       label: "Payments.PaymentLine",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-paymentline-modifier",
    //       label: "Payments.PaymentLine.Modifier",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-transaction",
    //       label: "Payments.Transaction",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-transactionstatus",
    //       label: "Payments.TransactionStatus",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-transactionerror",
    //       label: "Payments.TransactionError",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/payments-transactionerrorcode",
    //       label: "Payments.TransactionErrorCode",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/customeraddressdto",
    //       label: "CustomerAddressDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/customeraddressrequest",
    //       label: "CustomerAddressRequest",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/getpaymentgatewaysresponse",
    //       label: "GetPaymentGatewaysResponse",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/merchantpaymentgatewaydto",
    //       label: "MerchantPaymentGatewayDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentgateways-paymentgatewaydto",
    //       label: "PaymentGateways.PaymentGatewayDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paymentgateways-paymentgatewayparameterdto",
    //       label: "PaymentGateways.PaymentGatewayParameterDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/refundpaymentrequest-transaction",
    //       label: "RefundPaymentRequest.Transaction",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/refundpaymentrequest",
    //       label: "RefundPaymentRequest",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/paginationresponse-customeraddressdto",
    //       label: "PaginationResponse_CustomerAddressDto",
    //       className: "schema",
    //     },
    //     {
    //       type: "doc",
    //       id: "api/webapi/schemas/validationproblemdetails",
    //       label: "ValidationProblemDetails",
    //       className: "schema",
    //     },
    //   ],
    // },
  ],
};

export default sidebar.apisidebar;
