[build]
	command = "yarn build"
	publish = "build"

[[redirects]]
from = '/terms/vsa'
to = '/terms/service'

[[redirects]]
from = '/api/general/overview/'
to = '/api/webapi/voucherly-api/'

[[redirects]]
from = '/api/general/authentication/'
to = '/api/webapi/voucherly-api/'

[[redirects]]
from = '/api/general/miscellaneous/'
to = '/api/webapi/voucherly-api/'