import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apisidebar from './docs/api/webapi/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  apiSidebar: [
    {
      type: 'category',
      label: "General",
      collapsed: false,
      items: [
        ...apisidebar.slice(0, 1),
        {
          type: 'autogenerated',
          dirName: 'api/general'
        }
      ]
    },
    { type: 'doc', id: 'api/postman' },
    {
      type: 'category',
      label: "Libraries",
      collapsed: true,
      link: { type: "doc", id: "api/libraries/index" }, 
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/libraries/sdks'
        }
      ]
    },
    {
      type: 'category',
      label: "Endpoints 🔗",
      collapsed: false,
      collapsible: false,
      className: 'endpoint-section',
      items: [
        // Skipping "Introduction" section (automatically added) at first position in apisidebar 
        ...apisidebar.slice(1)
      ]
    },
  ]
};

export default sidebars;
