import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import apisidebar from './docs/api/webapi/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/introduction'
    },
    {
      type: 'doc',
      id: 'api/authentication'
    },
    {
      type: 'doc',
      id: 'api/errors'
    },
    {
      type: 'doc',
      id: 'api/miscellaneous'
    },
    {
      //type: 'autogenerated', 
      //dirName: 'api',
      type: 'category',
      label: 'Endpoints',
      items: apisidebar
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
